spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_batch_fetch_size: 100

---
spring.config.activate.on-profile: local

spring:
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true

storage:
  datasource:
    core:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:core;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=USER
      username: sa
      hikari:
        pool-name: core-db-pool
        data-source-properties:
          rewriteBatchedStatements: true

---
spring.config.activate.on-profile: dev

storage:
  datasource:
    core:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${CORE_DB_URL}
      username: ${CORE_DB_USERNAME}
      password: ${CORE_DB_PASSWORD}
      hikari:
        maximum-pool-size: 5
        connection-timeout: 1100
        keepalive-time: 30000
        validation-timeout: 1000
        max-lifetime: 600000
        pool-name: core-db-pool
        data-source-properties:
          socketTimeout: 3000
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
          useLocalSessionState: true
          rewriteBatchedStatements: true
          cacheResultSetMetadata: true
          cacheServerConfiguration: true
          elideSetAutoCommits: true
          maintainTimeStats: false
---
spring.config.activate.on-profile: live
storage:
  datasource:
    core:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${CORE_DB_URL}
      username: ${CORE_DB_USERNAME}
      password: ${CORE_DB_PASSWORD}
      hikari:
        maximum-pool-size: 25
        connection-timeout: 1100
        keepalive-time: 30000
        validation-timeout: 1000
        max-lifetime: 600000
        pool-name: core-db-pool
        data-source-properties:
          socketTimeout: 3000
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
          useLocalSessionState: true
          rewriteBatchedStatements: true
          cacheResultSetMetadata: true
          cacheServerConfiguration: true
          elideSetAutoCommits: true
          maintainTimeStats: false
