== 이슈 관련 API

=== [미구현] 이슈 생성

operation::append-issue[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== [미구현] 이슈 상세 조회

operation::find-issue[snippets='http-request,path-parameters,http-response,response-fields']

=== 이슈 이름 수정

operation::modify-issue-name[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== 이슈 내용 수정

operation::modify-issue-content[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== 이슈 담당자 수정

operation::modify-issue-assignee[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== 이슈 컴포넌트 수정

operation::modify-issue-component[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== 이슈 비즈포인트 수정

operation::modify-issue-bizpoint[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== 이슈 중요도 수정

operation::modify-issue-importance[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== [미구현] 이슈 에픽 수정

operation::modify-issue-epic[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== 이슈 진행 상태 수정

operation::modify-issue-status[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== [미구현] 에픽 하위 이슈 목록 조회

operation::find-epic-issues[snippets='http-request,path-parameters,http-response,response-fields']

=== [미구현] 스프린트 하위 이슈 목록 조회

operation::find-sprint-issues[snippets='http-request,path-parameters,http-response,response-fields']

=== [미구현] 컴포넌트 별 활성 스프린트 이슈 목록 조회

operation::find-component-issues[snippets='http-request,path-parameters,http-response,response-fields']

=== [미구현] 스프린트 내 이슈 이동

operation::modify-issue-sprint[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== [미구현] 나의 이슈 목록 조회

operation::find-my-issues[snippets='http-request,query-parameters,http-response,response-fields']